### ISSUE TITLE
attempt to compare nil with number

### ISSUE THREAD

**Issue by oalders** [ptdewey/yankbank-nvim#14]
Thanks for an excellent plugin! 

I just started seeing this a few days ago. I'm currently on 6bd9ca9. I'm happy to provide more context if needed.

```
Error detected while processing TextYankPost Autocommands for "*":
Error executing lua callback: ...share/nvim/lazy/yankbank-nvim/lua/yankbank/clipboard.lua:16: attempt to compare nil with number
stack traceback:
        ...share/nvim/lazy/yankbank-nvim/lua/yankbank/clipboard.lua:16: in function 'add_yank'
        ...share/nvim/lazy/yankbank-nvim/lua/yankbank/clipboard.lua:48: in function <...share/nvim/lazy/yankbank-nvim/lua/yankbank/clipboard.lua:28>
```

**Comment by ptdewey** [comment]
I'm not entirely sure what is causing that error, but I'd be happy to look into it. 
Can you send your plugin config and some more details about what you are doing when the error occurs?

**Comment by oalders** [comment]
Sure thing! My plugin config is at: https://github.com/oalders/dot-files/blob/main/nvim/lua/conf/lazy/init.lua#L205 and https://github.com/oalders/dot-files/blob/main/nvim/lua/plugins/init.lua#L88

If I open a new file and delete a line `dd`, then I get the message. If I open a new file and yank a line, then I also get the message.

However, after the initial interaction (delete or yank) on a particular line, the message goes away. So, I can `dd` and I get the message. If I revert the line and then yank it, there's no message. If I move down to a line which I have not deleted or yanked, the cycle with the message starts again.

**Comment by ptdewey** [comment]
What is the output of running `:set clipboard` in neovim?

In a clean build I was able to reproduce the issue when clipboard is not set, so I may investigate adding a check to see if the vim option is set.

**Comment by ptdewey** [comment]
Actually, the problem arose from a missing 'max_entries' option in init.lua, which should have been set by default but I must have messed up in a change in the last release. I have provided a fix for this issue in #15.

Please update the plugin and let me know if the issue persists

**Comment by oalders** [comment]
The output of `:set clipboard` is `clipboard=`.

Having said that, I've pulled in the latest version of the plugin and there are no more messages. Thanks so much for the speedy help! 🚀

**Comment by ilan-schemoul** [comment]
On latest version I have the same issue ubuntu 22 WSL 2.0
```vim
set clipboard?
clipboard=unnamedplus
```
I tried adding max_entries setting
```
return {
  "ptdewey/yankbank-nvim",
  opts = {
    max_entries = 9,
  },
}

```

**Comment by ptdewey** [comment]
> On latest version I have the same issue ubuntu 22 WSL 2.0
> 
> ```viml
> set clipboard?
> clipboard=unnamedplus
> ```
> 
> I tried adding max_entries setting
> 
> ```
> return {
>   "ptdewey/yankbank-nvim",
>   opts = {
>     max_entries = 9,
>   },
> }
> ```

Can you give me more details about what is causing the issue and the output (and what commit you are on)? I haven't been able to replicate the issue on my own WSL instance. Also, do you have xclip installed?
