### ISSUE TITLE
`keymaps` doesn't work

### ISSUE THREAD

**Issue by Jaehaks** [ptdewey/yankbank-nvim#21]
Thankyou for your efforts, 

`keymaps` option doesn't work as I think 

```lua
-- merge default and options keymap tables
local k = vim.tbl_deep_extend("force", default_keymaps, YB_OPTS.keymaps or {})
```
I  checked `YB_OPTS.keymaps` and it was `nil` when yankbank initialized.

**Comment by ptdewey** [comment]
What Neovim version are you using? 
I think the behavior of tbl_deep_extend changed in 0.11.0 so that may be the cause of the issue if you are using that version.
