### ISSUE TITLE
Allow overriding db path

### ISSUE THREAD

**Issue by Lewenhaupt** [ptdewey/yankbank-nvim#22]
I'm using Nix for neovim (and NixOs on my current install). I believe the proper way has been commented out and replaced because I'm using https://github.com/danielfalk/smart-open.nvim as well and the db can be created with the `vim.fn.stdpath("data")` variant.
The error: `sqlite.lua: couldn't connect to sql database, ERR: unable to open database file` and the cause is because the resolved dir is a writeonly dir in the nix store.

**Comment by ptdewey** [comment]
You can adjust the database path with the `db_path` option in the latest version.

This should work for you if you add it to your config options: `db_path = vim.fn.stdpath("data")`

**Comment by Lewenhaupt** [comment]
@ptdewey That works absolutely perfect :) Thanks a lot!
